# supabase/config.toml

project_id = "prfsoqztdanhkzyajjhk"

[api]
# The port to use for the API proxy.
port = 54321
# Schemas to expose in your API. Tables, views and stored procedures in these schemas will get API
# endpoints.
schemas = ["public", "storage", "graphql"]
# The maximum number of rows returns from a view, table, or function call.
max_rows = 1000

[db]
# The port to use for the local database.
port = 54322
# The database major version to use.
major_version = 15

[studio]
# The port to use for Supabase Studio.
port = 54323

# Email testing
# Use a command like `npx inbucket` to spin up a local SMTP server.
[inbucket]
# The port to use for the email testing server.
port = 54324
# The SMTP port to use for the email testing server.
smtp_port = 54325
# The POP3 port to use for the email testing server.
pop3_port = 54326

[functions]
[functions.delete-user]
enabled = true
verify_jwt = true
import_map = "./functions/delete-user/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/delete-user/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/delete-user/*.html" ]

[functions.export-user-data]
enabled = true
verify_jwt = true
import_map = "./functions/export-user-data/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/export-user-data/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/export-user-data/*.html" ]
