name: Send Order Reminders

on:
  schedule:
    # Runs every minute
    - cron: '* * * * *'
  workflow_dispatch: # Allows manual triggering

jobs:
  send_reminders:
    runs-on: ubuntu-latest
    steps:
      - name: Call Vercel API to send reminders
        run: |
          curl --request POST \
            --url 'https://restaurant-order-manager.vercel.app/api/send-reminders?x-vercel-set-bypass-cookie=true&x-vercel-protection-bypass=${{ secrets.VERCEL_BYPASS_TOKEN }}' \
            --header 'Authorization: Bearer ${{ secrets.CRON_SECRET }}'
