name: Send Order Reminders

on:
  schedule:
    # Runs every minute
    - cron: '* * * * *'
  workflow_dispatch: # Allows manual triggering

jobs:
  send_reminders:
    runs-on: ubuntu-latest
    steps:
      - name: Call Vercel API to send reminders
        run: |
          curl --request POST \
            --url 'https://prfsoqztdanhkzyajjhk.supabase.co/functions/v1/send-reminders' \
            --header 'Authorization: Bearer ${{ secrets.CRON_SECRET }}'
